[project]
name = "git-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.6.0",
    "python-dotenv>=0.20.0",
    "requests>=2.28.0",
]

[project.scripts]
git-diff = "git_diff:main"
